apiVersion: v1
kind: Service
metadata:
  name: my-spring-app
  labels:
    app: my-spring-app
spec:
  type: ClusterIP
  selector:
    app: my-spring-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP